import {defineApp,feature} from './domain-config.mjs';
export default defineApp({
  "id": "ai-hospital-transfer-drg-reimbursement-recovery",
  "engine": "recovery",
  "title": "Hospital Transfer DRG Reimbursement Recovery",
  "shortTitle": "Hospital Transfer DRG Reimbursement Recovery",
  "tagline": "Identify claims incorrectly reduced under transfer rules and recover the full DRG-supported reimbursement.",
  "industry": "Hospital Revenue Integrity",
  "buyer": "Acute-care hospitals and health systems",
  "uiPort": 4643,
  "apiPort": 5643,
  "accent": "#0369a1",
  "currency": "USD",
  "primaryOutcome": "Hospital Transfer DRG Reimbursement Recovery converted into governed, evidence-backed financial outcomes",
  "valueNarrative": "Connect admissions, discharge status, transfer destinations, DRG assignments, length of stay, post-acute claims, payer policies, remittances, and appeals in one accountable workflow. Identify claims incorrectly reduced under transfer rules and recover the full DRG-supported reimbursement.",
  "calculation": {
    "actualKey": "receivedAmount",
    "expectedKey": "entitledAmount",
    "actualLabel": "Received or Recognized Amount",
    "expectedLabel": "Contract or Rule-Supported Entitlement",
    "varianceLabel": "Unrecovered supported value",
    "direction": "expected-minus-actual",
    "finding": "Hospital Transfer DRG Reimbursement Recovery evidence indicates a measurable financial exception.",
    "actions": [
      "Validate the effective agreement, eligibility rules, and accountable parties",
      "Reconcile transaction-level operational and financial evidence",
      "Prepare the correction, recovery, or compliance package",
      "Track counterparty response, approval, cash, and preventive control closure"
    ]
  }
},[
feature("inpatient-claim-ingestion","HTD01","Inpatient claim ingestion","Execute inpatient claim ingestion using admissions, discharge status, transfer destinations, DRG assignments, length of stay, post-acute claims, payer policies, remittances, and appeals.","Produce a governed inpatient claim ingestion decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Hospital / Inpatient Claim","text","Hospital / Inpatient Claim · Standard Case"],["caseReference","Inpatient claim ingestion Reference","text","HTD01-2026-001"],["receivedAmount","Received or Recognized Amount","currency",507500],["entitledAmount","Contract or Rule-Supported Entitlement","currency",614075],["domainDriver","Transfer Disposition","select","Acute transfer",["Acute transfer","Post-acute transfer","Not a transfer"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["Inpatient claim ingestion case","Discharge status validation case","Transfer destination matching case","Post-acute claim linkage case","DRG transfer-rule library case"]}),
feature("discharge-status-validation","HTD02","Discharge status validation","Execute discharge status validation using admissions, discharge status, transfer destinations, DRG assignments, length of stay, post-acute claims, payer policies, remittances, and appeals.","Produce a governed discharge status validation decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Hospital / Inpatient Claim","text","Hospital / Inpatient Claim · Standard Case"],["caseReference","Discharge status validation Reference","text","HTD02-2026-001"],["receivedAmount","Received or Recognized Amount","currency",507500],["entitledAmount","Contract or Rule-Supported Entitlement","currency",614075],["domainDriver","Transfer Disposition","select","Acute transfer",["Acute transfer","Post-acute transfer","Not a transfer"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["Inpatient claim ingestion case","Discharge status validation case","Transfer destination matching case","Post-acute claim linkage case","DRG transfer-rule library case"]}),
feature("transfer-destination-matching","HTD03","Transfer destination matching","Execute transfer destination matching using admissions, discharge status, transfer destinations, DRG assignments, length of stay, post-acute claims, payer policies, remittances, and appeals.","Produce a governed transfer destination matching decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Hospital / Inpatient Claim","text","Hospital / Inpatient Claim · Standard Case"],["caseReference","Transfer destination matching Reference","text","HTD03-2026-001"],["receivedAmount","Received or Recognized Amount","currency",507500],["entitledAmount","Contract or Rule-Supported Entitlement","currency",614075],["domainDriver","Transfer Disposition","select","Acute transfer",["Acute transfer","Post-acute transfer","Not a transfer"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["Inpatient claim ingestion case","Discharge status validation case","Transfer destination matching case","Post-acute claim linkage case","DRG transfer-rule library case"]}),
feature("post-acute-claim-linkage","HTD04","Post-acute claim linkage","Execute post-acute claim linkage using admissions, discharge status, transfer destinations, DRG assignments, length of stay, post-acute claims, payer policies, remittances, and appeals.","Produce a governed post-acute claim linkage decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Hospital / Inpatient Claim","text","Hospital / Inpatient Claim · Standard Case"],["caseReference","Post-acute claim linkage Reference","text","HTD04-2026-001"],["receivedAmount","Received or Recognized Amount","currency",507500],["entitledAmount","Contract or Rule-Supported Entitlement","currency",614075],["domainDriver","Transfer Disposition","select","Acute transfer",["Acute transfer","Post-acute transfer","Not a transfer"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["Inpatient claim ingestion case","Discharge status validation case","Transfer destination matching case","Post-acute claim linkage case","DRG transfer-rule library case"]}),
feature("drg-transfer-rule-library","HTD05","DRG transfer-rule library","Execute drg transfer-rule library using admissions, discharge status, transfer destinations, DRG assignments, length of stay, post-acute claims, payer policies, remittances, and appeals.","Produce a governed drg transfer-rule library decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Hospital / Inpatient Claim","text","Hospital / Inpatient Claim · Standard Case"],["caseReference","DRG transfer-rule library Reference","text","HTD05-2026-001"],["receivedAmount","Received or Recognized Amount","currency",507500],["entitledAmount","Contract or Rule-Supported Entitlement","currency",614075],["domainDriver","Transfer Disposition","select","Acute transfer",["Acute transfer","Post-acute transfer","Not a transfer"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["Inpatient claim ingestion case","Discharge status validation case","Transfer destination matching case","Post-acute claim linkage case","DRG transfer-rule library case"]}),
feature("geometric-mean-los-validation","HTD06","Geometric mean LOS validation","Execute geometric mean los validation using admissions, discharge status, transfer destinations, DRG assignments, length of stay, post-acute claims, payer policies, remittances, and appeals.","Produce a governed geometric mean los validation decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Hospital / Inpatient Claim","text","Hospital / Inpatient Claim · Standard Case"],["caseReference","Geometric mean LOS validation Reference","text","HTD06-2026-001"],["receivedAmount","Received or Recognized Amount","currency",507500],["entitledAmount","Contract or Rule-Supported Entitlement","currency",614075],["domainDriver","Transfer Disposition","select","Acute transfer",["Acute transfer","Post-acute transfer","Not a transfer"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["Inpatient claim ingestion case","Discharge status validation case","Transfer destination matching case","Post-acute claim linkage case","DRG transfer-rule library case"]}),
feature("per-diem-payment-reconstruction","HTD07","Per-diem payment reconstruction","Execute per-diem payment reconstruction using admissions, discharge status, transfer destinations, DRG assignments, length of stay, post-acute claims, payer policies, remittances, and appeals.","Produce a governed per-diem payment reconstruction decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Hospital / Inpatient Claim","text","Hospital / Inpatient Claim · Standard Case"],["caseReference","Per-diem payment reconstruction Reference","text","HTD07-2026-001"],["receivedAmount","Received or Recognized Amount","currency",507500],["entitledAmount","Contract or Rule-Supported Entitlement","currency",614075],["domainDriver","Transfer Disposition","select","Acute transfer",["Acute transfer","Post-acute transfer","Not a transfer"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["Inpatient claim ingestion case","Discharge status validation case","Transfer destination matching case","Post-acute claim linkage case","DRG transfer-rule library case"]}),
feature("same-day-readmission-analysis","HTD08","Same-day readmission analysis","Execute same-day readmission analysis using admissions, discharge status, transfer destinations, DRG assignments, length of stay, post-acute claims, payer policies, remittances, and appeals.","Produce a governed same-day readmission analysis decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Hospital / Inpatient Claim","text","Hospital / Inpatient Claim · Standard Case"],["caseReference","Same-day readmission analysis Reference","text","HTD08-2026-001"],["receivedAmount","Received or Recognized Amount","currency",507500],["entitledAmount","Contract or Rule-Supported Entitlement","currency",614075],["domainDriver","Transfer Disposition","select","Acute transfer",["Acute transfer","Post-acute transfer","Not a transfer"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["Inpatient claim ingestion case","Discharge status validation case","Transfer destination matching case","Post-acute claim linkage case","DRG transfer-rule library case"]}),
feature("interrupted-stay-review","HTD09","Interrupted stay review","Execute interrupted stay review using admissions, discharge status, transfer destinations, DRG assignments, length of stay, post-acute claims, payer policies, remittances, and appeals.","Produce a governed interrupted stay review decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Hospital / Inpatient Claim","text","Hospital / Inpatient Claim · Standard Case"],["caseReference","Interrupted stay review Reference","text","HTD09-2026-001"],["receivedAmount","Received or Recognized Amount","currency",507500],["entitledAmount","Contract or Rule-Supported Entitlement","currency",614075],["domainDriver","Transfer Disposition","select","Acute transfer",["Acute transfer","Post-acute transfer","Not a transfer"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["Inpatient claim ingestion case","Discharge status validation case","Transfer destination matching case","Post-acute claim linkage case","DRG transfer-rule library case"]}),
feature("payer-policy-versioning","HTD10","Payer policy versioning","Execute payer policy versioning using admissions, discharge status, transfer destinations, DRG assignments, length of stay, post-acute claims, payer policies, remittances, and appeals.","Produce a governed payer policy versioning decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Hospital / Inpatient Claim","text","Hospital / Inpatient Claim · Standard Case"],["caseReference","Payer policy versioning Reference","text","HTD10-2026-001"],["receivedAmount","Received or Recognized Amount","currency",507500],["entitledAmount","Contract or Rule-Supported Entitlement","currency",614075],["domainDriver","Transfer Disposition","select","Acute transfer",["Acute transfer","Post-acute transfer","Not a transfer"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["Inpatient claim ingestion case","Discharge status validation case","Transfer destination matching case","Post-acute claim linkage case","DRG transfer-rule library case"]}),
feature("underpayment-detection","HTD11","Underpayment detection","Execute underpayment detection using admissions, discharge status, transfer destinations, DRG assignments, length of stay, post-acute claims, payer policies, remittances, and appeals.","Produce a governed underpayment detection decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Hospital / Inpatient Claim","text","Hospital / Inpatient Claim · Standard Case"],["caseReference","Underpayment detection Reference","text","HTD11-2026-001"],["receivedAmount","Received or Recognized Amount","currency",507500],["entitledAmount","Contract or Rule-Supported Entitlement","currency",614075],["domainDriver","Transfer Disposition","select","Acute transfer",["Acute transfer","Post-acute transfer","Not a transfer"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["Inpatient claim ingestion case","Discharge status validation case","Transfer destination matching case","Post-acute claim linkage case","DRG transfer-rule library case"]}),
feature("corrected-claim-generation","HTD12","Corrected claim generation","Execute corrected claim generation using admissions, discharge status, transfer destinations, DRG assignments, length of stay, post-acute claims, payer policies, remittances, and appeals.","Produce a governed corrected claim generation decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Hospital / Inpatient Claim","text","Hospital / Inpatient Claim · Standard Case"],["caseReference","Corrected claim generation Reference","text","HTD12-2026-001"],["receivedAmount","Received or Recognized Amount","currency",507500],["entitledAmount","Contract or Rule-Supported Entitlement","currency",614075],["domainDriver","Transfer Disposition","select","Acute transfer",["Acute transfer","Post-acute transfer","Not a transfer"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["Inpatient claim ingestion case","Discharge status validation case","Transfer destination matching case","Post-acute claim linkage case","DRG transfer-rule library case"]}),
feature("appeal-evidence-package","HTD13","Appeal evidence package","Execute appeal evidence package using admissions, discharge status, transfer destinations, DRG assignments, length of stay, post-acute claims, payer policies, remittances, and appeals.","Produce a governed appeal evidence package decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Hospital / Inpatient Claim","text","Hospital / Inpatient Claim · Standard Case"],["caseReference","Appeal evidence package Reference","text","HTD13-2026-001"],["receivedAmount","Received or Recognized Amount","currency",507500],["entitledAmount","Contract or Rule-Supported Entitlement","currency",614075],["domainDriver","Transfer Disposition","select","Acute transfer",["Acute transfer","Post-acute transfer","Not a transfer"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["Inpatient claim ingestion case","Discharge status validation case","Transfer destination matching case","Post-acute claim linkage case","DRG transfer-rule library case"]}),
feature("remittance-reconciliation","HTD14","Remittance reconciliation","Execute remittance reconciliation using admissions, discharge status, transfer destinations, DRG assignments, length of stay, post-acute claims, payer policies, remittances, and appeals.","Produce a governed remittance reconciliation decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Hospital / Inpatient Claim","text","Hospital / Inpatient Claim · Standard Case"],["caseReference","Remittance reconciliation Reference","text","HTD14-2026-001"],["receivedAmount","Received or Recognized Amount","currency",507500],["entitledAmount","Contract or Rule-Supported Entitlement","currency",614075],["domainDriver","Transfer Disposition","select","Acute transfer",["Acute transfer","Post-acute transfer","Not a transfer"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["Inpatient claim ingestion case","Discharge status validation case","Transfer destination matching case","Post-acute claim linkage case","DRG transfer-rule library case"]}),
feature("facility-drg-analytics","HTD15","Facility DRG analytics","Execute facility drg analytics using admissions, discharge status, transfer destinations, DRG assignments, length of stay, post-acute claims, payer policies, remittances, and appeals.","Produce a governed facility drg analytics decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Hospital / Inpatient Claim","text","Hospital / Inpatient Claim · Standard Case"],["caseReference","Facility DRG analytics Reference","text","HTD15-2026-001"],["receivedAmount","Received or Recognized Amount","currency",507500],["entitledAmount","Contract or Rule-Supported Entitlement","currency",614075],["domainDriver","Transfer Disposition","select","Acute transfer",["Acute transfer","Post-acute transfer","Not a transfer"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["Inpatient claim ingestion case","Discharge status validation case","Transfer destination matching case","Post-acute claim linkage case","DRG transfer-rule library case"]})
]);
